// File: insideT.v
// Generated by MyHDL 1.0dev
// Date: Thu Oct 13 21:34:05 2016


`timescale 1ns/10ps

module insideT (
    out,
    ptx,
    pty,
    p1x,
    p1y,
    p2x,
    p2y,
    p3x,
    p3y
);


output out;
wire out;
input [9:0] ptx;
input [9:0] pty;
input [9:0] p1x;
input [9:0] p1y;
input [9:0] p2x;
input [9:0] p2y;
input [9:0] p3x;
input [9:0] p3y;

wire s1;
wire s2;
wire s3;




assign s1 = ((($signed({1'b0, ptx}) - $signed({1'b0, p2x})) * ($signed({1'b0, p1y}) - $signed({1'b0, p2y}))) < (($signed({1'b0, p1x}) - $signed({1'b0, p2x})) * ($signed({1'b0, pty}) - $signed({1'b0, p2y}))));



assign s2 = ((($signed({1'b0, ptx}) - $signed({1'b0, p3x})) * ($signed({1'b0, p2y}) - $signed({1'b0, p3y}))) < (($signed({1'b0, p2x}) - $signed({1'b0, p3x})) * ($signed({1'b0, pty}) - $signed({1'b0, p3y}))));



assign s3 = ((($signed({1'b0, ptx}) - $signed({1'b0, p1x})) * ($signed({1'b0, p3y}) - $signed({1'b0, p1y}))) < (($signed({1'b0, p3x}) - $signed({1'b0, p1x})) * ($signed({1'b0, pty}) - $signed({1'b0, p1y}))));



assign out = ((s1 == s2) & (s2 == s3));

endmodule
